<template>
  <div id="twic-short-videos-container">
    <TwicWrapper git-hub-url="pages/short-videos.vue">
      <TwicAbstract title="Short Videos">
        <p>
          The ideal candidates for TwicPics video integration are hero videos,
          product videos, and thumbnails.
        </p>
        <p>
          All videos generated by the TwicPics API are muted, to be looped and
          played automatically. You can think of them as GIFs, but with high
          quality.
        </p>
        <p>
          The TwicVideo component automatically handles CLS, LQIP and the
          display of a generated poster until the video is actually viewable.
        </p>
        <p>
          This feature is available
          <strong>for all our Pro and Enterprise customers</strong>.
        </p>
        <br />
        Here the properties used in this example:
        <ul>
          <li>
            <TwicCode>intrinsic</TwicCode>:
            <span
              >prevents video upscaling and limits the number of generated
              variants.</span
            >
          </li>
          <li>
            <TwicCode>focus</TwicCode>:<span
              >changes the focus point coordinates of the image.</span
            >
          </li>
          <li>
            <TwicCode>mode</TwicCode>:<span
              >determines if the image fills or sits inside the area.</span
            >
          </li>
          <li>
            <TwicCode>placeholder</TwicCode>:
            <span
              >helps optimize your CLS and implement the LQIP technique.</span
            >
          </li>
          <li>
            <TwicCode>ratio</TwicCode>:
            <span>
              &nbsp; determines the value of the width/height ratio of the image
              display area.
            </span>
          </li>
        </ul>
      </TwicAbstract>
      <div class="twic-grid">
        <div class="twic-item">
          <TwicVideo
            src="video/skater.mp4"
            intrinsic="1280x720"
            placeholder="preview"
            ratio="16/9"
          />
          <span>
            <TwicCode>ratio="16/9"</TwicCode>&<TwicCode>mode="cover"</TwicCode>:
            the video fills the area
          </span>
        </div>
        <div class="twic-item">
          <TwicVideo
            src="video/skater.mp4"
            focus="center"
            intrinsic="1280x720"
            mode="cover"
            placeholder="maincolor"
          />
          <span> Default values </span>
        </div>
        <div class="twic-item">
          <TwicVideo
            src="video/skater.mp4"
            intrinsic="1280x720"
            placeholder="meancolor"
            mode="contain"
            ratio="1"
          />
          <span>
            <TwicCode>ratio="1"</TwicCode>&<TwicCode>mode="contain"</TwicCode>:
            the video sits inside the area
          </span>
        </div>
        <div class="twic-item">
          <TwicVideo
            src="video/skater.mp4"
            intrinsic="1280x720"
            placeholder="preview"
            ratio="2/3"
          />
          <span>
            <TwicCode>ratio="2/3"</TwicCode>,<TwicCode>mode="cover"</TwicCode>:
            the video fills the area
          </span>
        </div>
      </div>
    </TwicWrapper>
  </div>
</template>
<script>
export default {
  name: 'TwicShortVideo',
}
</script>
<style lang="scss">
#twic-short-videos-container {
  .twic-item .twic-w {
    background-color: #00ffa3;
    display: block;
  }
}
</style>
